language: python
python:
  - "3.6"
  - "3.7"
install:
  # Install Anaconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -c rdkit -n test-env rdkit python=$TRAVIS_PYTHON_VERSION
  - source activate test-env
  - conda install pandas natsort openpyxl xlrd xlwt

# command to run tests
script:
  - nosetests