language: python
python:
  - "3.6"
install:
  # Install Anaconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export PATH="/home/travis/miniconda/bin:$PATH"
  - export PATH="/home/travis/miniconda/envs"
  - hash -r
  - conda update -q conda
  - conda info -a
  - conda create -c rdkit -n testenv rdkit python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest pytest-cov
# command to run tests
script:
  - pytest --cov=./

after_success:
- codecov