language: python
python: 3.8.5
jobs:
  include:
    - name: "Python 3.8 on Linux"
      python: 3.8.5
      before_install:
        - pip3 install -r requirements.txt
    - name: "Python 3.8 on macOS"
      os: osx
      osx_image: xcode12
      language: shell
      before_install:
        - brew update
        - brew install pyenv
        - brew install pyenv
        - brew install pyenv-virtualenv
        - echo 'eval "$(pyenv init -)"' >> ~/.zshrc
        - echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.zshrc
        - source ~/.zshrc
        - pyenv install 3.8.3
        - pyenv virtualenv 3.8.3 envlynx
        - pyenv activate envlynx
        - python -m pip install --upgrade pip
        - pip3 install --user -r requirements.txt
    - name: "Python 3.8 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.5
        - python -m pip install --upgrade pip
        - pip3 install -r requirements.txt
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
  - pip3 install codecov==2.1.7 coverage==5.1 pytest==5.4.3 pytest-cov==2.10.0
script:
  - pytest --cov=./
after_success:
  - codecov