language: python

python:
- 3.7

matrix:
  include:
  - os: linux
    python: 3.7
    install:
      - pip install -r requirements.txt
      - pip install codecov
      - pip install pytest pytest-cov
    script:
    - pytest --cov=./
    after_success:
    - codecov

  - os: osx
    python: 3.7
    language: sh
    install:
      - pip install -r requirements.txt
      - pip install codecov
      - pip install pytest pytest-cov
    # command to run tests
    script:
      - pytest --cov=./
    after_success:
      - codecov

  - os: windows
    python: 3.7
    language: sh
    install:
      - echo $PATH
      - pip install -r requirements.txt
      - pip install codecov
      - pip install pytest pytest-cov
    # command to run tests
    script:
      - pytest --cov=./
    after_success:
      - codecov