name: testenv
channels:
  - rdkit
  - defaults
dependencies:
  - flask
  - natsort
  - numba
  - numexpr
  - numpy
  - numpy-base
  - openpyxl
  - pandas
  - python
  - rdkit
  - requests
  - xlrd
  - xlwt

